import type {
  RestaurantWithRelations,
  ToEatItem,
  VisitWithRelations,
} from "@/lib/types";

export const demoRestaurants: RestaurantWithRelations[] = [
  {
    id: "demo-restaurant-1",
    user_id: "demo",
    name: "Kanada-Ya",
    city: "London",
    country: "United Kingdom",
    address: "64 St Giles High St, London",
    latitude: 51.515,
    longitude: -0.13,
    cuisine_type: "Japanese",
    average_price: 18,
    currency: "GBP",
    provider_place_id: null,
    provider_name: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    visits: [],
    dishes: [],
    photos: [],
  },
  {
    id: "demo-restaurant-2",
    user_id: "demo",
    name: "Four Seasons",
    city: "London",
    country: "United Kingdom",
    address: "12 Gerrard St, London",
    latitude: 51.512,
    longitude: -0.131,
    cuisine_type: "Cantonese",
    average_price: 28,
    currency: "GBP",
    provider_place_id: null,
    provider_name: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    visits: [],
    dishes: [],
    photos: [],
  },
];

export const demoVisits: VisitWithRelations[] = [
  {
    id: "demo-visit-1",
    user_id: "demo",
    restaurant_id: "demo-restaurant-1",
    visit_date: new Date().toISOString().slice(0, 10),
    taken_at: new Date().toISOString(),
    companions: null,
    average_price: 18,
    total_score: 4.5,
    taste_score: null,
    environment_score: null,
    service_score: null,
    value_score: null,
    will_revisit: "Yes",
    summary: "Rich broth, fast solo dinner, easy revisit.",
    detailed_review: null,
    recommended_dishes: "Tonkotsu ramen",
    bad_dishes: null,
    suitable_scenarios: ["solo meal", "quick dinner", "ramen"],
    location_source: "device",
    location_confidence: "medium",
    restaurant_match_source: "manual",
    ai_generated: true,
    user_confirmed: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    restaurants: demoRestaurants[0],
    dishes: [
      {
        id: "demo-dish-1",
        user_id: "demo",
        restaurant_id: "demo-restaurant-1",
        visit_id: "demo-visit-1",
        name: "Tonkotsu ramen",
        name_ai_guess: "Pork ramen",
        cuisine_guess: "Japanese",
        category: "main",
        visible_ingredients: ["noodles", "egg", "spring onion"],
        score: null,
        price: null,
        currency: "GBP",
        is_recommended: true,
        is_bad: false,
        comment: null,
        ai_confidence: "medium",
        user_confirmed: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    photos: [],
  },
];

export const demoToEatItems: ToEatItem[] = [
  {
    id: "demo-to-eat-1",
    user_id: "demo",
    title: "Try the crispy duck rice from a saved video",
    source_url: "https://www.xiaohongshu.com/explore/demo",
    source_platform: "xiaohongshu",
    source_creator: "London food note",
    restaurant_name: "Four Seasons",
    city: "London",
    address: "Gerrard St",
    cuisine_type: "Cantonese",
    note: "Looks good for friends visiting Chinatown.",
    tags: ["duck", "friends", "chinatown"],
    priority: 4,
    status: "to_eat",
    shareable: true,
    linked_restaurant_id: null,
    linked_visit_id: null,
    source_share_token: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-to-eat-2",
    user_id: "demo",
    title: "Save ramen spot from Douyin",
    source_url: "https://www.douyin.com/video/demo",
    source_platform: "douyin",
    source_creator: "Food finder",
    restaurant_name: "Kanada-Ya",
    city: "London",
    address: null,
    cuisine_type: "Japanese",
    note: "Check queue time before going.",
    tags: ["ramen", "solo meal"],
    priority: 3,
    status: "to_eat",
    shareable: false,
    linked_restaurant_id: null,
    linked_visit_id: null,
    source_share_token: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
